### ISSUE TITLE
Questions about PTT module

### ISSUE THREAD

**Issue by freshwk** [shanjiayao/PTT#3]
Hi，I'm trying to reproduce your work. But i can't achieve the same result as you. I have several questions as follow:
1、 Could you please tell me the difference between the PTT module in your work and the transformer block in the work "Point transformer". When i try to reproduce your work, i I use the transformer block in the work "Point transformer" directly. 
2、How do you set the parameter "k" when you use K-nearest-neighbor (KNN) to get position encoding.

**Comment by shanjiayao** [comment]
Hi, thank you for your interest in our project! @freshwk 

I am so sorry that the release of the paper and code is late since our work has been further expanded as a journal paper some time ago, there are certain changes in the code. Recently, I have been cleaning the code and preparing to open source. 

Regarding the PTT module, our final result is indeed the use of the Point Transformer structure, because the performance of this structure was found to be the best during the experiment. Hence, we set K = 16.

Regarding our work, a more detailed journal version has been written, and you can see more detailed ablation experiments after the journal is accepted.

**Comment by freshwk** [comment]
> Hi, thank you for your interest in our project! @freshwk
> 
> I am so sorry that the release of the paper and code is late since our work has been further expanded as a journal paper some time ago, there are certain changes in the code. Recently, I have been cleaning the code and preparing to open source.
> 
> Regarding the PTT module, our final result is indeed the use of the Point Transformer structure, because the performance of this structure was found to be the best during the experiment. Hence, we set K = 16.
> 
> Regarding our work, a more detailed journal version has been written, and you can see more detailed ablation experiments after the journal is accepted.

Thank you for your reply!  Good luck to you!
