### ISSUE TITLE
ubuntu qt.qpa.xcb: could not connect to display

### ISSUE THREAD

**Issue by chenqi13814529300** [shanjiayao/PTT#8]
I got an error when connecting to Ubuntu training using FinalShell on my MAC

ubuntu qt.qpa.xcb: could not connect to display

Can you tell me how to solve the problem, I reproduce the P2B code is successful

**Comment by shanjiayao** [comment]
Sorry I haven't tested our code on the Mac. Regarding the qt-related errors you mentioned, I can only guess that it is probably related to the visual code.

Please check the installation of `pyqt`, `mayavi`, `vtk` and if there are calls like `import mayavi` and `mayavi_show` in the code you are running?

**Comment by chenqi13814529300** [comment]
Thanks, I have replicated successfully, I now use the window system, demo_tracking.py run failed, can you take an example, the parameters are not clear what it means

**Comment by shanjiayao** [comment]
Please give the specific error message so that I can check the code error.

PS： In fact, demo_tracking.py is used to debug when you change the network architecture. Hence, you don't need to run demo_tracking.py, just follow the [README](https://github.com/shanjiayao/PTT#quickstart) to train and test.

**Comment by chenqi13814529300** [comment]
Thank you very much for your help, I am also interested in this article
